version: '3.9'


volumes:
  data:

services:
  database:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=server2023
    volumes:
      - data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
