version: '3.9'

services:
  mysql:
    image: mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=server2022
      - MYSQL_PASSWORD=server2021
      - MYSQL_USER=administrador
      - MYSQL_DATABASE=alura
